stages:
  - qualidade
  - build
  - deploy
  - notificacao

services:
  - docker:dind

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task

sonarcloud-check:
  stage: qualidade
  tags:
    - docker
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  only: &varqualidade
    variables:
      - $EXECUTAR == "deploy"
      - $EXECUTAR == "qualidade"

Verificar Compose:
  stage: qualidade
  only: *varqualidade
  tags:
    - shell
  script:
    - docker-compose config -q
    - echo $?

build-docker-image:
  image: docker:latest
    stage: build
    variables:
    IMAGE: ${CI_REGISTRY_USER}/simpleapp:latest
    script:
      - "docker build -t ${CI_REGISTRY_USER}/simpleapp:latest ."
      - "docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}"
      - "docker push ${CI_REGISTRY_USER}/simpleapp:latest"

build:
  stage: build
  tags:
    - shell
  only: &vardeploy
    variables:
      - $EXECUTAR == "deploy"
  script:
    - |
        if [ -e "/storage/wordpress/html" ]
        then
          echo " o diretorio existe"
          sudo rsync -avh --progress wordpress/* /storage/wordpress/html/
        else
          echo " o diretorio não existe, vamos cria-lo e fazer deploy"
          sudo mkdir -p /storage/wordpress/html/
          sudo rsync -avh --progress wordpress/* /storage/wordpress/html/
        fi

Deploy wordpress:
  stage: deploy
  tags:
    - shell
  only: *vardeploy
  script:
    - sudo chown -R 33:33 /storage/wordpress/html/
    - docker-compose down
    - sleep 10
    - docker-compose up -d

Verificar deploy:
  stage: deploy
  tags:
    - shell
  only: *vardeploy
  dependencies:
    - "Deploy wordpress"
  script:
    - sleep 10
    - curl -v http://10.0.2.15:8000
    - echo $?

Notificar Sucesso:
  stage: notificacao
  tags:
    - shell
  only: *vardeploy
  when: on_success
  script:
    - source notificacaoSucesso.sh

Notificar Falha:
  stage: notificacao
  tags:
    - shell
  only: *vardeploy
  when: on_failure
  script:
    - source notificacaoFalha.sh
